name: Build and Push Airflow Image

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build_push_airflow_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Checkout ff
      uses: FedericoCarboni/setup-ffmpeg@v1

    - name: Run bash script with arguments
      run: ffmpeg -nostdin -hide_banner -re -i rtsp://admin:Emngu125@kuratajr.gotdns.ch:620/onvif2 -t 20 -c:v libx264 -vf scale=1280:720 $RUNNER_TEMP/output.avi

    - name: Cat file
      run: ls -l $RUNNER_TEMP/