name: Build and Push Airflow Image

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build_push_airflow_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Checkout ff
      uses: FedericoCarboni/setup-ffmpeg@v2

    - name: Run bash script with arguments
      run: echo "This is the contents of my file." > $RUNNER_TEMP/output.txt

    - name: Cat file
      run: cat $RUNNER_TEMP/output.txt