name: Build and Push Airflow Image

env:
  RUNNER_ALLOW_RUNASROOT: 1

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build_push_airflow_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Checkout ff
      uses: FedericoCarboni/setup-ffmpeg@v2

    - id: setup-ffmpeg
      run: ffmpeg -i rtsp://admin:Emngu125@kuratajr.gotdns.ch:620/onvif2 -t 30 -c:v libx264 -vf scale=1280:720 $RUNNER_TEMP/output.mkv

    - name: Cat file
      run: ls -l $RUNNER_TEMP/