name: Record RTSP stream to Google Drive
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  record-rtsp-stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ffmpeg
        run: sudo apt-get install ffmpeg

      - name: Install gsutil
        run: sudo apt-get install gsutil

      - name: Set variables
        env:
          URL: 'rtsp://admin:Kurata1909@21.209.162.229:2500/onvif1'
          FILE=$(date "+%y%m%d-%H%M%S")-imou1.mp4

      - name: Record video
        run: ffmpeg -i "$URL" -c:v copy -c:a copy -f mp4 -b:v 20M -vf scale=1280:720 "$FILE"

      - name: Upload video to Google Drive
        run: gsutil cp "$FILE" gdrive:/my-folder/
